spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/jpaNewTimeApiDemo?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.ddl-auto: none
      hibernate.connection.provider_disables_autocommit: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.id.new_generator_mappings: true
      hibernate.jdbc.time_zone: UTC
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false